### PR TITLE
add support for SolidJS

### PR DESCRIPTION
**Pull request by Artemis69**
I have doubts about some things, and some things are unfinished. 🧜‍♀️

### CODE REVIEW

**Comment by Valexr** [comment]
Oh, good approach 👍🏻
Adapted @slidy/svelte for Solid?

**Comment by Valexr** [comment]
@Artemis69 TX 🎉 for you contribution 🤓 i'm merged it & can you continue mainten this?

**Comment by Valexr** [comment]
@Artemis69 TX 🎉 for you contribution 🤓 i'm merging it if you can continue mainten this?

**Comment by Artemis69** [comment]
> @Artemis69 TX 🎉 for you contribution 🤓 i'm merged it & can you continue mainten this?

Maintain... I could try it, but I'm not sure there will be much free time in 6 months, 1 year, or 2. So solid will be released a little later than svelte.

I would like to mention that some parts are not ready, and also I have not checked the slots at all

**Comment by Valexr** [comment]
> > @Artemis69 TX 🎉 for you contribution 🤓 i'm merged it & can you continue mainten this?
> 
> Maintain... I could try it, but I'm not sure there will be much free time in 6 months, 1 year, or 2. So solid will be released a little later than svelte.
> 
> I would like to mention that some parts are not ready, and also I have not checked the slots at all

How it will be convenient🤓
Welcome ✌🏻

**Comment by Artemis69** [comment]
If you are more or less satisfied with the current implementation, you can merge it 😶

**Pull request merged**
